# Настройки ORM
datasource:
  # Задаём базу данных, к которой будет происходить подключение
  db:
    username: "admin"
    password: "admin"
    url: "jdbc:h2:~/hexlet"

# Заполняем базу данных первоначальными данными
ebean:
  db:
    ddl:
      generate: true
      run: true
      seedSql: seed.sql
